### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by Pompeiro** [skasero/LoL-TFT-Bot#2]
Hey, what about working together on TFT bot?

**Comment by skasero** [comment]
@Pompeiro I took look at the bot you've created and I'm very impressed with what you've got working. I would be interested in trying to work on a bot together.

**Comment by Pompeiro** [comment]
@skasero the best way to contact me is to find me on Discord Papaj#3719 . If u dont use Discord then let me know.

**Comment by skasero** [comment]
@Pompeiro I added you on discord. My discord name is Lexical.
